### ISSUE TITLE
Надпись о версии для разработки так и не появляется

### ISSUE THREAD

**Issue by heartofdalek** [GerasimovRuslan/bitrix-dev-mode#2]
После запуска cli-версии отсутствует надпись
_"Эта установка предназначена для разработки на базе продукта "1С-Битрикс: Управление сайтом". Она не должна использоваться в качестве рабочего (боевого) сайта."_
Т.е. ядро продолжнает считать, что это обычная версия, но без ключа.

**Comment by GerasimovRuslan** [comment]
Баг исправил
